name: backend-lint-and-test
on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.py'
      - '**/pyproject.toml'
      - '**/poetry.lock'
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install packages
        run: python -m pip install black flake8
  format:
    name: format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run black
        run: python3.8 -m black .
  lint:
    name: lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run flake8
        run: python3.8 -m flake8 .
