name: backend-lint-and-test
on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.py'
      - '**/pyproject.toml'
      - '**/poetry.lock'
jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - name: Run black
        run: python3.8 -m black .
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - name: Run flake8
        run: python3.8 -m flake8 .
