name: backend-lint-and-test
on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.py'
      - '**/pyproject.toml'
      - '**/poetry.lock'
jobs:
  setup:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  format:
    name: format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - python -m pip install black
      - python3.8 -m black .
  lint:
    name: lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - python -m pip install flake8
      - python3.8 -m flake8 .
